module.exports = async ({ github, context, core }) => {
  const { owner, repo } = context.repo;

  const version = process.env.NEWEST_VERSION;
  const branchName = process.env.PREVIEW_BRANCH;
  const title = `Artifacts updated v${version}`;
  const body = `## Artifacts update

WhatsApp Web has been updated to version **${version}**.

---
*This PR was automatically generated by the update workflow.*`;

  const pr = await github.rest.pulls.create({
    owner,
    repo,
    head: branchName,
    base: "main",
    title,
    body,
  });

  await github.rest.issues.addLabels({
    owner,
    repo,
    issue_number: pr.data.number,
    labels: ["automated", "artifacts"],
  });

  await github.rest.pulls.requestReviewers({
    owner,
    repo,
    pull_number: pr.data.number,
    reviewers: ["jaovitubr"],
  });

  core.info(`PR criado: #${pr.data.number}`);
};