name: Publish

on:
  pull_request:
    types: [closed]
    branches:
      - main

env:
  PACKAGE_TAG: latest
  BRANCH: ${{ github.event.pull_request.head.ref }}
  OUT_DIR: ${{ github.workspace }}/out
  DIST_DIR: ${{ github.workspace }}/out/dist

permissions:
  id-token: write
  contents: write
  checks: write
  pull-requests: write

jobs:
  latest:
    if: >-
      github.event.pull_request.merged == true &&
      startsWith(github.event.pull_request.head.ref, 'preview/')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH }}

      - name: Set up environment
        run: |
          git config --global user.name "GitHub Actions [Bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          VERSION=$(cat out/.version)

          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Publishing version: $VERSION"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: Generate packages
        id: generate_packages
        run: bash generate.sh
        working-directory: tools/packager

      - name: Publish packages
        run: bash publish.sh
        working-directory: tools/packager

      - name: Create Git tag
        run: |
          git tag -a "v$VERSION" -m "WhatsApp Web v$VERSION"
          git push origin "v$VERSION"

      - name: Delete merged branch
        run: |
          git push origin --delete $BRANCH